FROM ubuntu:latest

RUN sudo apt-get update -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

RUN sudo apt-get install -y git

CMD ["/bin/bash"]